apiVersion : apps/v1
kind: Deployment
metadata:
  name: gecommercestore 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gecommercestore
  template:
    metadata:
      labels:
        app: gecommercestore 
    spec:
      containers:
        - name: gecommercestore 
          image: crecommerceauto.azurecr.io/gecommercestore
          ports:
          - containerPort: 3001
          env:
            - name: NODE_ENV
              value: production
            - name: NEXT_PUBLIC_API_URL
              value: "http://20.242.151.101:3000/api/99986257-a0e5-42f5-a9f4-b9fe8cebead0"
            - name: REACT_EDITOR
              value: "atom"