apiVersion: v1
kind: Service
metadata:
    name: gecommercestore
spec:
    type: LoadBalancer
    ports:
        - name: http
          protocol: TCP
          port: 3001
          targetPort: 3001 
    selector:
        app: gecommercestore